BlogSitesi/Models/AboutViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BlogSitesi.Models
{
    public class AboutViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Başlık")]
        [Required(ErrorMessage = "Hakkımda bilgisini göstermek için bu alan zorunludur.")]
        [MinLength(4, ErrorMessage = "{0} için en az {1} karakter giriniz !")]
        [MaxLength(20,ErrorMessage = "{0} en fazla {1} karakter uzunluğunda veri girişi yapabilirsiniz !")]
        public string TitleName { get; set; }

        
        [Display(Name = "İçerik")]
        [Required(ErrorMessage = "Hakkımda bilgisinin içeriği burada değiştirilmelidir.")]
        [AllowHtml] //requestlere kod yazmasına bile izin verir.

        public string AboutDescription { get; set; }


    }
}

BlogSitesi/Models/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BlogSitesi.Models
{
    public class ContactViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Ad")]
        [Required(ErrorMessage = "İletişim bilgisini göstermek için bu alan zorunludur.")]
        [MinLength(4,ErrorMessage = "{0} için en az {1} karakter giriniz !")]
        [MaxLength(50,ErrorMessage = "{0} için en fazla {1} karakter uzunluğunda veri girişi yapabilirsiniz !")]
        public string FullName { get; set; }
        
        [Display(Name = "İletişim Numarası")]
        [Required(ErrorMessage = "İletişim numarasını göstermek için bu alan zorunludur.")]
        public string PhoneNumber { get; set; }
        
        [Display(Name = "Mail adresi")]
        [Required(ErrorMessage = "Mail adresinin bilgisi için bu alan zorunludur")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Geçersiz E Mail adresi")]
        public string EmailAddress { get; set; }

    }
}

BlogSitesi/Areas/Admin/Controllers/AboutController.cs
using System.Web.Mvc;
using BlogSitesi.Extensions;
using BlogSitesi.Models;
using BlogSitesi.Services;

namespace BlogSitesi.Areas.Admin.Controllers
{
    public class AboutController : Controller
    {
        private AboutPageService _aboutPageService;

        public AboutController()
        {
            _aboutPageService = new AboutPageService();
        }

        [HttpGet]
        public ActionResult Index()
        {
            var about = _aboutPageService.GeAboutPage();

            var viewModel = about.GetAboutViewModel();

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var aboutModel = _aboutPageService.GeAboutPage();

            var aboutViewModel = aboutModel.GetAboutViewModel();

            return View(aboutViewModel);
        }

        [HttpPost]
        public ActionResult Edit(AboutViewModel aboutViewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("TitleName","İçeriği düzenleyebilmek için gerekli tüm alanları doldurmanız gerekmektedir");
                return View();
            }

            var aboutPage = aboutViewModel.GetAboutPage();
            _aboutPageService.UpdateAbout(aboutPage);
            return RedirectToAction("Index");
        }


    }
}

BlogSitesi/Areas/Admin/Controllers/ContactController.cs
using System.Web.Mvc;
using BlogSitesi.Extensions;
using BlogSitesi.Models;
using BlogSitesi.Services;

namespace BlogSitesi.Areas.Admin.Controllers
{
    public class ContactController : Controller
    {
        private ContactPageService _contactPageService;

        public ContactController()
        {
             _contactPageService=new ContactPageService();
        }

        [HttpGet]
        public ActionResult Index()
        {
            var contact = _contactPageService.GetContactPage();

            var viewModel = contact.GetContactViewModel(); 
        
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var contactModel = _contactPageService.GetContactPage();

            var contactViewModel = contactModel.GetContactViewModel();

            return View(contactViewModel);
        }

        [HttpPost]
        public ActionResult Edit(ContactViewModel contactViewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("TitleName","İçeriği düzenleyebilmek için gerekli tüm alanları doldurmanız gerekmektedir.");
                return View();
            }

            var contactPage = contactViewModel.GetContactPage();
            _contactPageService.UpdateContact(contactPage);
            return RedirectToAction("Index");
        }

    }
}

BlogSitesi/Areas/Admin/Controllers/HomeController.cs
using System.Web.Mvc;

namespace BlogSitesi.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

BlogSitesi/Controllers/HomeController.cs
using System.Web.Mvc;
using BlogSitesi.Extensions;
using BlogSitesi.Services;


namespace BlogSitesi.Controllers
{
    public class HomeController : Controller
    {

        private readonly AboutPageService _aboutPageService;
        private readonly ContactPageService _contactPageService;

        public HomeController()
        {
                _aboutPageService=new AboutPageService();
                _contactPageService=new ContactPageService();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]

        public ActionResult About()
        {
            var about = _aboutPageService.GeAboutPage();
            var viewModel = about.GetAboutViewModel();

            return View(viewModel);
        }


        [HttpGet]
        public ActionResult Contact()
        {
            var contact = _contactPageService.GetContactPage();
            var viewModel = contact.GetContactViewModel();

            return View(viewModel);

        }
    }
}

BlogSitesi/Areas/Admin/Views/About/Edit.cshtml
@model AboutViewModel
@{
    ViewBag.AdminTitle = "About Düzenleme Ekranı";
}

@section customAdminScripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

@using (Html.BeginForm("Edit", "About", FormMethod.Post))
{
    @Html.HiddenFor(i => i.Id)

    <div class="form-group">
        <div class="row">
            @Html.ValidationSummary("", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-2">
                @Html.DisplayNameFor(i => i.TitleName)
            </div>
            <div class="col">

                @Html.TextBoxFor(model => model.TitleName, new { @class = "form-control", placeholder = "Başlık giriniz" })
                @Html.ValidationMessageFor(i => i.TitleName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-2">
                @Html.LabelFor(i => i.AboutDescription)
            </div>
            <div class="col">

                @Html.EditorFor(model => model.AboutDescription, new { htmlAttributes = new { @class = "form-control", placeholder = "İçerik giriniz", required = "required" } })
                @Html.ValidationMessageFor(i => i.AboutDescription, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Kaydet ve Gönder" class="btn btn-info" />
    </div>


}

BlogSitesi/Areas/Admin/Views/About/Index.cshtml
@model AboutViewModel

@{
    ViewBag.AdminTitle = "Hakkımda içeriği";
}

<hr/>
<a href="@Url.Action("Edit")" class="btn btn-outline-primary btn-block">Düzenle</a>
<br/>
<h2 class="text-center">@Model.TitleName</h2>

<br/>
@Html.Raw(@Model.AboutDescription)


    

BlogSitesi/Areas/Admin/Views/Contact/Edit.cshtml
@model ContactViewModel
@{
    ViewBag.ContactTitle = "Contact Düzenleme Ekranı";
}
@section customAdminScripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

@using (Html.BeginForm("Edit", "Contact", FormMethod.Post))
{
    @Html.HiddenFor(i => i.Id)

    <div class="form-group">
        <div class="row">
            @Html.ValidationSummary("", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-2">
                @Html.DisplayNameFor(i => i.FullName)
            </div>
            <div class="col">

                @Html.TextBoxFor(model => model.FullName, new { @class = "form-control", placeholder = "Ad giriniz" })
                @Html.ValidationMessageFor(i => i.FullName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-2">
                @Html.DisplayNameFor(i => i.PhoneNumber)
            </div>
            <div class="col">
                @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", placeholder = "İletişim numarası giriniz: " })
                @Html.ValidationMessageFor(i => i.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-2">
                @Html.LabelFor(i => i.EmailAddress)
            </div>
            <div class="col">
                @Html.TextBoxFor(model => model.EmailAddress, new { @class = "form-control", placeholder = "Mail adresi giriniz: " })
                @Html.ValidationMessageFor(i => i.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Kaydet ve Gönder" class="btn btn-info" />
    </div>
    

}

BlogSitesi/Areas/Admin/Views/Contact/Index.cshtml
@model ContactViewModel

@{
    ViewBag.AdminTitle = "İletişim Sayfasındaki İçerikler";
}

<hr />

<a href="@Url.Action("Edit")" class="btn btn-outline-primary btn-block">Düzenle</a>
<br />
<div class="container" style="text-align:center">
    <h2>İletişim Sayfasındaki İçerikler</h2>
    <ul class="list-unstyled">
        <li><b>Adı: </b>@Model.FullName</li>
        <li><b>Mail Adresi: </b>@Model.EmailAddress </li>
        <li><b>İletişim numarası: </b>@Model.PhoneNumber</li>
    </ul>

</div>

BlogSitesi/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.AdminTitle = "Admin Paneli";
}

<div class="row">
    <p>Bu alana genellikle raporlarımızı, chartlarımızı ve çeşitli sık kullanılan yerlerin bilgilerini koyarız</p>
</div>

BlogSitesi/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.AdminTitle</title>

    <link href="~/Content/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    @RenderSection("customAdminStyles", false)

</head>
<body class="container-fluid">
    

    @*Burası NavBar*@
    @Html.Partial("_AdminNavBar")



    <div class="container">
        @RenderBody()
    </div>

    <script src="~/Content/lib/jQuery/jquery-3.3.1.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/css/_LayoutStyleSheet.css" rel="stylesheet" />
    @RenderSection("customAdminScripts", false)

</body>
</html>

BlogSitesi/Areas/Admin/Views/Shared/_AdminNavBar.cshtml
<div class="row">

    <div class="col">
        <a href="@Url.Action("Index", "Home", new {area = ""})" target="_blank">
            Anasayfa
        </a>
    </div>

    <div class="col">
        <a href="@Url.Action("Index", "Home", new {area = "Admin"})">Admin Anasayfa</a>
    </div>

    <div class="col">
        <a href="@Url.Action("Index", "About", new {area = "Admin"})">Admin About</a>
    </div>

    <div class="col">
        <a href="@Url.Action("Index", "Contact", new {area = "Admin"})">Admin Contact</a>
    </div>


</div>

BlogSitesi/Views/Home/About.cshtml
@model BlogSitesi.Models.AboutViewModel
@{
    ViewBag.Title = "Hakkımda Sayfası";
    
}

<h2>@Model.TitleName</h2>
<p style="text-align:center">@Html.Raw(Model.AboutDescription)</p>

BlogSitesi/Views/Home/Contact.cshtml
@model BlogSitesi.Models.ContactViewModel
@{
    ViewBag.Title = "İletişim Bilgileri";

}

<div class="container" style="text-align:center">
    <h2>@ViewBag.Title</h2>
    <ul class="list-unstyled">
        <li><b>Adı: </b>@Model.FullName</li>
        <li><b>Mail Adresi: </b>@Model.EmailAddress </li>
        <li><b>İletişim numarası: </b>@Model.PhoneNumber</li>
    </ul>

</div>

BlogSitesi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Anasayfa";
}


@*Kart İçerikleri*@
<div class="card-columns">
    <div class="card">

        <img src="~/Content/images/1world.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Card title that wraps to a new line</h5>
            <p class="card-text">Yaklaşık 5 yıldır dünyadaki gelişmeleri takip etmeye odaklanan Dünya Halleri sitesi, yayın hayatına bugün itibarıyla son veriyor.</p>
        </div>
    </div>
    <div class="card p-3">
        <blockquote class="blockquote mb-0 card-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">
                <small class="text-muted">
                    Someone famous in <cite title="Source Title">Source Title</cite>
                </small>
            </footer>
        </blockquote>
    </div>
    <div class="card">

        <img src="~/Content/images/2.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Haftanın Spor Özeti: 59</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
    </div>
    <div class="card bg-primary text-white text-center p-3">
        <blockquote class="blockquote mb-0">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat.</p>
            <footer class="blockquote-footer text-white">
                <small>
                    Someone famous in <cite title="Source Title">Source Title</cite>
                </small>
            </footer>
        </blockquote>
    </div>
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text">This card has a regular title and short paragraphy of text below it.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
    </div>
    <div class="card">
        <img src="~/Content/images/3.jpg" class="card-img-top" alt="...">
    </div>
    <div class="card p-3 text-right">
        <blockquote class="blockquote mb-0">
            <p>Dizel araçları elektrikliye dönüştüren girişim</p>
            <footer class="blockquote-footer">
                <small class="text-muted">
                    Someone famous in <cite title="Source Title">Source Title</cite>
                </small>
            </footer>
        </blockquote>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Dizel araçları elektrikliye dönüştüren girişim</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
    </div>
</div>

BlogSitesi/Views/Shared/_Footer.cshtml
<footer id="footer">

    <ul id="footerul">
        <li id="footerli">
            <a id="footer-a" href="#">Takip et!</a>
        </li>

        <li id="footerli">
            <a href="#">Arama</a>
        </li>

        <li id="footerli">
            <a href="@Url.Action("Contact","Home")">İletişim</a>
        </li>

        <li id="footerli">
            <a href="@Url.Action("About","Home")>Künye</a>
        </li>
    </ul>
</footer>

BlogSitesi/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Takip Et! <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Arama</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Contact","Home")">İletişim</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("About","Home")">Künye</a>
            </li>
          
        </ul>
    </div>
</nav>

BlogSitesi/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    @RenderSection("customStyles",false)

</head>
<body>

    <div class="container-fluid">

        @*Header*@
        @Html.Partial("_Header")
        @*For image logo*@
        <div class="container" id="DunyaHalleriImage"><a href="@Url.Action("Index","Home")"><img src="~/Content/images/1.png" /></a></div>
        @*NAVBAR*@
        @Html.Partial("_Navbar")

        @RenderBody()
        <!-- Footer -->
        @Html.Partial("_Footer")

    </div>
    <script src="~/Content/lib/jQuery/jquery-3.3.1.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.js"></script>
<link href="~/Content/css/_LayoutStyleSheet.css" rel="stylesheet" />
@RenderSection("customScripts",false)
</body>
</html>

BlogSitesi/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-primary" id="NavBar">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")" style="color:white;font-weight:bold; padding:13px;">Anasayfa <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("About","Home")" style="color:white; font-weight:bold;padding:13px;">Hakkımda</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Contact","Home")" style="color:white; font-weight:bold;padding:13px;">İletişim</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Home",new{area="Admin"})" target="_blank" style="color:white; font-weight:bold;padding:13px;">Yönetici Girişi</a>
            </li>
        </ul>
    </div>
</nav>

BlogSitesi/Views/Shared/_NotFound.cshtml
Veri tabanında gösterilecek veri bulunamadı !!!